name: d3d-dxvk-sarek-async-arm64ec

on:
  workflow_dispatch:
    inputs:
      host:
        type: boolean
        default: false
        description: "Self-hosted"
      version:
        type: string
        description: "(v1.10.8, v1.11.0) Empty = Latest"

  schedule:
    - cron: "0 17 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  GH_TOKEN:        ${{ github.token }}
  UNI_KIND:        dxvk-sarek-async-arm64ec
  REL_TAG_STABLE:  DXVK-SAREK-ASYNC-ARM64EC
  UPSTREAM_REPO:   pythonlover02/DXVK-Sarek
  UPSTREAM_BRANCH: async

defaults:
  run:
    shell: 'bash --noprofile --norc -Eeuo pipefail {0}'

jobs:
  guard:
    name: Build Guard
    runs-on: ${{ inputs.host == true && 'self-hosted' || 'ubuntu-latest' }}
    timeout-minutes: 5
    env:
      IN_CHANNEL:  stable
      IN_VERSION:  ${{ github.event_name == 'workflow_dispatch' && inputs.version || '' }}
      IS_SCHEDULE: ${{ github.event_name == 'schedule' }}
    outputs:
      missing: ${{ steps.check.outputs.missing }}
      list:    ${{ steps.check.outputs.list }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check Upstream & Queue
        id: check
        run: bash ./scripts/guard.sh

  build:
    name: Build & Pack
    needs: guard
    if: needs.guard.outputs.missing == 'true'
    runs-on: ${{ inputs.host == true && 'self-hosted' || 'ubuntu-latest' }}
    timeout-minutes: 60
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Deps
        run: bash ./scripts/install-deps-ubuntu.sh

      - name: Setup Build Env (Meson + llvm-mingw)
        run: bash ./scripts/setup-llvm-meson.sh

      - name: Clone Source
        run: |
          git clone "https://github.com/$UPSTREAM_REPO.git" src
          git -C src config user.name "Builder"
          git -C src config user.email "bot@noreply"

      - name: Build Loop
        env:
          TO_BUILD: ${{ needs.guard.outputs.list }}
        run: |
          mkdir -p _logs out src/out

          cd src
          git fetch --tags --force

          while IFS='|' read -r kind channel ref ver_name ver_code rel_tag rel_title filename short; do
            [[ -n "$kind" ]] || continue

            if [[ -z "$ref" ]]; then
              echo "::warning::Skipping queue line with empty ref (raw kind='$kind')" >&2
              continue
            fi

            LOG_PATH="../_logs/${UNI_KIND}-${ver_name}-build.log"

            {
              echo "::group::Building ${ref} (${ver_name})"

              # 1. Clean & Checkout                              async branch
              git reset --hard
              git clean -fdx
              
              git fetch origin "$UPSTREAM_BRANCH"
              git checkout -B "$UPSTREAM_BRANCH" "origin/$UPSTREAM_BRANCH"
              
              # 1.1 Submodule
              git submodule sync --recursive
              git submodule update --init --recursive

              # 2. Apply patches
              bash ../scripts/patches/dxvk.sh .
              . ../scripts/patches/dxvk-sarek-arm64ec.sh .

              # 3. Build Process (Custom for ARM64EC)
              ../.venv/bin/meson --version || true
              PKG_ROOT="../pkg_temp/${UNI_KIND}-${ref}"
              rm -rf "${PKG_ROOT}"
              mkdir -p "${PKG_ROOT}"

              rm -rf build_x86 build_ec

              # 3-1. Build x86 (Standard 32-bit)
              echo "Compiling x86 (32-bit)..."
              meson setup build_x86 \
                --cross-file build-win32.txt \
                --buildtype release \
                --prefix "$PWD/${PKG_ROOT}/x32"
              ninja -C build_x86 install

              # 3-2. Build ARM64EC (Replaces x64)
              echo "Compiling ARM64EC..."
              # shim flag
              ARGS_FLAGS="-I$MOCK_DIR -include sarek_all_in_one.h"
              
              CFLAGS="${CFLAGS:-}" \
              CXXFLAGS="$ARGS_FLAGS ${CXXFLAGS:-}" \
              meson setup build_ec \
                --cross-file ../toolchains/arm64ec.meson.ini \
                --buildtype release \
                --prefix "$PWD/${PKG_ROOT}/arm64ec" \
                -Dcpp_args="$ARGS_FLAGS"
              ninja -C build_ec install

              # 4. Resolve source dirs
              WCP_DIR="../${REL_TAG_STABLE}_WCP"
              rm -rf "$WCP_DIR"

              SRC_EC="${PKG_ROOT}/arm64ec"
              SRC_32="${PKG_ROOT}/x32"

              # Prefer /bin subfolder if present
              if [[ -d "$SRC_EC/bin" ]]; then
                SRC_EC="$SRC_EC/bin"
              fi

              if [[ -d "$SRC_32/bin" ]]; then
                SRC_32="$SRC_32/bin"
              fi

              # 5. Pack WCP
              PROFILE_SH="../scripts/profiles/${UNI_KIND}.sh" \
              bash ../scripts/packing.sh \
                "$SRC_EC" \
                "$SRC_32" \
                "$WCP_DIR" \
                "$ver_name" \
                "../out/${filename}"
            
              echo "::endgroup::"
            } 2>&1 | tee "$LOG_PATH"

          done <<< "$TO_BUILD"

      - name: Process Logs
        if: always()
        run: bash ./scripts/log.sh _logs/*.log

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REL_TAG_STABLE }}-logs
          path: _logs/

      - name: Release
        env:
          REPO:           ${{ github.repository }}
          REL_TAG:        ${{ env.REL_TAG_STABLE }} 
          VERSION_PREFIX: "${{ env.UNI_KIND }}-"
          ARTIFACT_GLOB:  "out/${{ env.UNI_KIND }}-*.wcp"
          BODY: |
            - Architecture: Arm64EC (system32) + x86 (syswow64)
            - **Exclusive to FEX**
            - **Patched: NEON-backed SSE shim**
        run: bash ./scripts/release.sh

  bump-readme:
    needs: build
    uses: ./.github/workflows/chore_purrrser.yml
    secrets: inherit
