#  /\_/\
# (=•ᆽ•=)づ🕔
name: chore-purrrger

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  maintenance:
    name: Refresh pack.json + README
    uses: ./.github/workflows/chore_purrrser.yml
    secrets: inherit
    permissions:
      contents: write
